{"date":"Mon Apr 17 2017 22:42:41 GMT+0530 (India Standard Time)","process":{"pid":5112,"uid":null,"gid":null,"cwd":"E:\\projects\\chatapp\\chatio","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v7.7.3","argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\chatapp\\chatio\\server.js"],"memoryUsage":{"rss":44761088,"heapTotal":32673792,"heapUsed":18931540,"external":18624852}},"os":{"loadavg":[0,0,0],"uptime":4431.0693038},"trace":[{"column":11,"file":"util.js","function":"Object.exports._errnoException","line":1033,"method":"exports._errnoException","native":false},{"column":20,"file":"util.js","function":"exports._exceptionWithHostPort","line":1056,"method":"_exceptionWithHostPort","native":false},{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1099,"method":"afterConnect [as oncomplete]","native":false}],"stack":["Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","    at Object.exports._errnoException (util.js:1033:11)","    at exports._exceptionWithHostPort (util.js:1056:20)","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"],"level":"error","message":"uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","timestamp":"2017-04-17T17:12:41.210Z"}
{"date":"Mon Apr 17 2017 22:42:41 GMT+0530 (India Standard Time)","process":{"pid":5112,"uid":null,"gid":null,"cwd":"E:\\projects\\chatapp\\chatio","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v7.7.3","argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\chatapp\\chatio\\server.js"],"memoryUsage":{"rss":45240320,"heapTotal":33198080,"heapUsed":19120756,"external":18624852}},"os":{"loadavg":[0,0,0],"uptime":4431.0849038},"trace":[{"column":11,"file":"util.js","function":"Object.exports._errnoException","line":1033,"method":"exports._errnoException","native":false},{"column":20,"file":"util.js","function":"exports._exceptionWithHostPort","line":1056,"method":"_exceptionWithHostPort","native":false},{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1099,"method":"afterConnect [as oncomplete]","native":false}],"stack":["Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","    at Object.exports._errnoException (util.js:1033:11)","    at exports._exceptionWithHostPort (util.js:1056:20)","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"],"level":"error","message":"uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","timestamp":"2017-04-17T17:12:41.210Z"}
{"date":"Mon Apr 17 2017 22:42:41 GMT+0530 (India Standard Time)","process":{"pid":5112,"uid":null,"gid":null,"cwd":"E:\\projects\\chatapp\\chatio","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v7.7.3","argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\chatapp\\chatio\\server.js"],"memoryUsage":{"rss":45514752,"heapTotal":33198080,"heapUsed":19375868,"external":18624852}},"os":{"loadavg":[0,0,0],"uptime":4431.8649051},"trace":[{"column":35,"file":"E:\\projects\\chatapp\\chatio\\node_modules\\mongodb-core\\lib\\topologies\\server.js","function":"","line":327,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitOne","line":96,"method":null,"native":false},{"column":7,"file":"events.js","function":"Pool.emit","line":191,"method":"emit","native":false},{"column":12,"file":"E:\\projects\\chatapp\\chatio\\node_modules\\mongodb-core\\lib\\connection\\pool.js","function":"","line":274,"method":null,"native":false},{"column":19,"file":"events.js","function":"Object.onceWrapper","line":293,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"emitTwo","line":106,"method":null,"native":false},{"column":7,"file":"events.js","function":"Connection.emit","line":194,"method":"emit","native":false},{"column":49,"file":"E:\\projects\\chatapp\\chatio\\node_modules\\mongodb-core\\lib\\connection\\connection.js","function":"","line":177,"method":null,"native":false},{"column":19,"file":"events.js","function":"Object.onceWrapper","line":293,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"emitOne","line":96,"method":null,"native":false},{"column":7,"file":"events.js","function":"Socket.emit","line":191,"method":"emit","native":false},{"column":8,"file":"net.js","function":"connectErrorNT","line":1034,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":80,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":104,"method":"_tickCallback","native":false}],"stack":["MongoError: failed to connect to server [<MongoDBHost>:27017] on first connect [MongoError: getaddrinfo ENOTFOUND <MongoDBHost> <MongoDBHost>:27017]","    at Pool.<anonymous> (E:\\projects\\chatapp\\chatio\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:35)","    at emitOne (events.js:96:13)","    at Pool.emit (events.js:191:7)","    at Connection.<anonymous> (E:\\projects\\chatapp\\chatio\\node_modules\\mongodb-core\\lib\\connection\\pool.js:274:12)","    at Object.onceWrapper (events.js:293:19)","    at emitTwo (events.js:106:13)","    at Connection.emit (events.js:194:7)","    at Socket.<anonymous> (E:\\projects\\chatapp\\chatio\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)","    at Object.onceWrapper (events.js:293:19)","    at emitOne (events.js:96:13)","    at Socket.emit (events.js:191:7)","    at connectErrorNT (net.js:1034:8)","    at _combinedTickCallback (internal/process/next_tick.js:80:11)","    at process._tickCallback (internal/process/next_tick.js:104:9)"],"level":"error","message":"uncaughtException: failed to connect to server [<MongoDBHost>:27017] on first connect [MongoError: getaddrinfo ENOTFOUND <MongoDBHost> <MongoDBHost>:27017]","timestamp":"2017-04-17T17:12:41.990Z"}
{"date":"Mon Apr 17 2017 22:42:42 GMT+0530 (India Standard Time)","process":{"pid":5112,"uid":null,"gid":null,"cwd":"E:\\projects\\chatapp\\chatio","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v7.7.3","argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\chatapp\\chatio\\server.js"],"memoryUsage":{"rss":45690880,"heapTotal":33198080,"heapUsed":19551496,"external":18633044}},"os":{"loadavg":[0,0,0],"uptime":4432.3173059},"trace":[{"column":11,"file":"util.js","function":"Object.exports._errnoException","line":1033,"method":"exports._errnoException","native":false},{"column":20,"file":"util.js","function":"exports._exceptionWithHostPort","line":1056,"method":"_exceptionWithHostPort","native":false},{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1099,"method":"afterConnect [as oncomplete]","native":false}],"stack":["Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","    at Object.exports._errnoException (util.js:1033:11)","    at exports._exceptionWithHostPort (util.js:1056:20)","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"],"level":"error","message":"uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","timestamp":"2017-04-17T17:12:42.442Z"}
{"date":"Mon Apr 17 2017 22:42:42 GMT+0530 (India Standard Time)","process":{"pid":5112,"uid":null,"gid":null,"cwd":"E:\\projects\\chatapp\\chatio","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v7.7.3","argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\chatapp\\chatio\\server.js"],"memoryUsage":{"rss":45748224,"heapTotal":33198080,"heapUsed":19609392,"external":18633044}},"os":{"loadavg":[0,0,0],"uptime":4432.348506},"trace":[{"column":11,"file":"util.js","function":"Object.exports._errnoException","line":1033,"method":"exports._errnoException","native":false},{"column":20,"file":"util.js","function":"exports._exceptionWithHostPort","line":1056,"method":"_exceptionWithHostPort","native":false},{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1099,"method":"afterConnect [as oncomplete]","native":false}],"stack":["Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","    at Object.exports._errnoException (util.js:1033:11)","    at exports._exceptionWithHostPort (util.js:1056:20)","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"],"level":"error","message":"uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","timestamp":"2017-04-17T17:12:42.473Z"}
{"date":"Mon Apr 17 2017 22:42:43 GMT+0530 (India Standard Time)","process":{"pid":5112,"uid":null,"gid":null,"cwd":"E:\\projects\\chatapp\\chatio","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v7.7.3","argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\chatapp\\chatio\\server.js"],"memoryUsage":{"rss":45813760,"heapTotal":33198080,"heapUsed":19674832,"external":18633044}},"os":{"loadavg":[0,0,0],"uptime":4433.6901084},"trace":[{"column":11,"file":"util.js","function":"Object.exports._errnoException","line":1033,"method":"exports._errnoException","native":false},{"column":20,"file":"util.js","function":"exports._exceptionWithHostPort","line":1056,"method":"_exceptionWithHostPort","native":false},{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1099,"method":"afterConnect [as oncomplete]","native":false}],"stack":["Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","    at Object.exports._errnoException (util.js:1033:11)","    at exports._exceptionWithHostPort (util.js:1056:20)","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"],"level":"error","message":"uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","timestamp":"2017-04-17T17:12:43.815Z"}
{"date":"Mon Apr 17 2017 22:42:43 GMT+0530 (India Standard Time)","process":{"pid":5112,"uid":null,"gid":null,"cwd":"E:\\projects\\chatapp\\chatio","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v7.7.3","argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\chatapp\\chatio\\server.js"],"memoryUsage":{"rss":45871104,"heapTotal":33198080,"heapUsed":19733624,"external":18633044}},"os":{"loadavg":[0,0,0],"uptime":4433.7057084},"trace":[{"column":11,"file":"util.js","function":"Object.exports._errnoException","line":1033,"method":"exports._errnoException","native":false},{"column":20,"file":"util.js","function":"exports._exceptionWithHostPort","line":1056,"method":"_exceptionWithHostPort","native":false},{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1099,"method":"afterConnect [as oncomplete]","native":false}],"stack":["Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","    at Object.exports._errnoException (util.js:1033:11)","    at exports._exceptionWithHostPort (util.js:1056:20)","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"],"level":"error","message":"uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","timestamp":"2017-04-17T17:12:43.831Z"}
